# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FrmCheckout.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(911, 539)
        Dialog.setMinimumSize(QtCore.QSize(911, 539))
        Dialog.setMaximumSize(QtCore.QSize(911, 539))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 911, 541))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("assets/images/imagen_login1.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(80, 10, 731, 511))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("border-radius: 7px; background-color: #F4F6F6;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(400, 30, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 221, 61))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("assets/images/unnamed.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(360, 210, 121, 1))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.GB_precioryc = QtWidgets.QGroupBox(self.frame)
        self.GB_precioryc.setGeometry(QtCore.QRect(340, 80, 371, 271))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        self.GB_precioryc.setFont(font)
        self.GB_precioryc.setStyleSheet("QGroupBox {\n"
"    border: 2px solid Black;\n"
"    border-radius: 5px;\n"
"}")
        self.GB_precioryc.setObjectName("GB_precioryc")
        self.TW_productos = QtWidgets.QTableWidget(self.GB_precioryc)
        self.TW_productos.setGeometry(QtCore.QRect(40, 30, 301, 131))
        self.TW_productos.setStyleSheet("QHeaderView::section {\n"
"    background-color: #2C3E50;\n"
"    color: white;\n"
"    padding: 5px;\n"
"    border: 1px solid #1A252F;\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QHeaderView::section:hover {\n"
"    background-color: #1ABC9C;\n"
"}")
        self.TW_productos.setRowCount(3)
        self.TW_productos.setObjectName("TW_productos")
        self.TW_productos.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.TW_productos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TW_productos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TW_productos.setHorizontalHeaderItem(2, item)
        self.TW_productos.verticalHeader().setVisible(False)
        self.PB_cargar_e = QtWidgets.QPushButton(self.GB_precioryc)
        self.PB_cargar_e.setGeometry(QtCore.QRect(140, 220, 111, 31))
        self.PB_cargar_e.setStyleSheet("QPushButton {\n"
"    background-color: #2C3E50;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #16A085;\n"
"}")
        self.PB_cargar_e.setObjectName("PB_cargar_e")
        self.CB_producto = QtWidgets.QComboBox(self.GB_precioryc)
        self.CB_producto.setGeometry(QtCore.QRect(80, 170, 131, 31))
        self.CB_producto.setStyleSheet("QComboBox {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}")
        self.CB_producto.setObjectName("CB_producto")
        self.SB_cantidad = QtWidgets.QSpinBox(self.GB_precioryc)
        self.SB_cantidad.setGeometry(QtCore.QRect(290, 170, 51, 31))
        self.SB_cantidad.setStyleSheet("QSpinBox {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QSpinBox:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}")
        self.SB_cantidad.setObjectName("SB_cantidad")
        self.label_12 = QtWidgets.QLabel(self.GB_precioryc)
        self.label_12.setGeometry(QtCore.QRect(250, 170, 31, 31))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("assets/icons/cantidad.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_11 = QtWidgets.QLabel(self.GB_precioryc)
        self.label_11.setGeometry(QtCore.QRect(40, 170, 31, 31))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("assets/icons/agregar-producto.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.GB_datos_cliente = QtWidgets.QGroupBox(self.frame)
        self.GB_datos_cliente.setGeometry(QtCore.QRect(30, 80, 281, 231))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        self.GB_datos_cliente.setFont(font)
        self.GB_datos_cliente.setStyleSheet("QGroupBox {\n"
"    border: 2px solid Black;\n"
"    border-radius: 5px;\n"
"}")
        self.GB_datos_cliente.setObjectName("GB_datos_cliente")
        self.LE_numero_d = QtWidgets.QLineEdit(self.GB_datos_cliente)
        self.LE_numero_d.setGeometry(QtCore.QRect(50, 60, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(9)
        self.LE_numero_d.setFont(font)
        self.LE_numero_d.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}")
        self.LE_numero_d.setReadOnly(True)
        self.LE_numero_d.setPlaceholderText("Documento de identidad")
        self.LE_numero_d.setObjectName("LE_numero_d")
        self.label_2 = QtWidgets.QLabel(self.GB_datos_cliente)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 31, 31))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("assets/icons/carnet-de-identidad.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.LE_nombres_apellidos = QtWidgets.QLineEdit(self.GB_datos_cliente)
        self.LE_nombres_apellidos.setGeometry(QtCore.QRect(50, 100, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(9)
        self.LE_nombres_apellidos.setFont(font)
        self.LE_nombres_apellidos.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}")
        self.LE_nombres_apellidos.setReadOnly(True)
        self.LE_nombres_apellidos.setPlaceholderText("Nombres y apellidos")
        self.LE_nombres_apellidos.setObjectName("LE_nombres_apellidos")
        self.label_8 = QtWidgets.QLabel(self.GB_datos_cliente)
        self.label_8.setGeometry(QtCore.QRect(10, 100, 31, 31))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("assets/icons/usuario (1).png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.LE_contacto = QtWidgets.QLineEdit(self.GB_datos_cliente)
        self.LE_contacto.setGeometry(QtCore.QRect(50, 140, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(9)
        self.LE_contacto.setFont(font)
        self.LE_contacto.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}")
        self.LE_contacto.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.LE_contacto.setReadOnly(True)
        self.LE_contacto.setPlaceholderText("Contacto")
        self.LE_contacto.setObjectName("LE_contacto")
        self.label_9 = QtWidgets.QLabel(self.GB_datos_cliente)
        self.label_9.setGeometry(QtCore.QRect(10, 140, 31, 31))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("assets/icons/llamada-telefonica.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.PB_buscar = QtWidgets.QPushButton(self.GB_datos_cliente)
        self.PB_buscar.setGeometry(QtCore.QRect(190, 20, 71, 31))
        self.PB_buscar.setStyleSheet("QPushButton {\n"
"    background-color: #2C3E50;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #16A085;\n"
"}")
        self.PB_buscar.setObjectName("PB_buscar")
        self.CB_numero_h = QtWidgets.QComboBox(self.GB_datos_cliente)
        self.CB_numero_h.setGeometry(QtCore.QRect(50, 20, 131, 31))
        self.CB_numero_h.setStyleSheet("QComboBox {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}\n"
"")
        self.CB_numero_h.setObjectName("CB_numero_h")
        self.label_19 = QtWidgets.QLabel(self.GB_datos_cliente)
        self.label_19.setGeometry(QtCore.QRect(10, 20, 31, 31))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("assets/icons/cama (1).png"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.PB_cargar = QtWidgets.QPushButton(self.GB_datos_cliente)
        self.PB_cargar.setGeometry(QtCore.QRect(60, 190, 171, 31))
        self.PB_cargar.setStyleSheet("QPushButton {\n"
"    background-color: #2C3E50;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #16A085;\n"
"}")
        self.PB_cargar.setObjectName("PB_cargar")
        self.GB_total_c = QtWidgets.QGroupBox(self.frame)
        self.GB_total_c.setGeometry(QtCore.QRect(340, 360, 371, 111))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        self.GB_total_c.setFont(font)
        self.GB_total_c.setStyleSheet("QGroupBox {\n"
"    border: 2px solid Black;\n"
"    border-radius: 5px;\n"
"}")
        self.GB_total_c.setObjectName("GB_total_c")
        self.CB_medio_p = QtWidgets.QComboBox(self.GB_total_c)
        self.CB_medio_p.setGeometry(QtCore.QRect(230, 20, 131, 31))
        self.CB_medio_p.setStyleSheet("QComboBox {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}\n"
"")
        self.CB_medio_p.setObjectName("CB_medio_p")
        self.LE_monto_a = QtWidgets.QLineEdit(self.GB_total_c)
        self.LE_monto_a.setGeometry(QtCore.QRect(50, 60, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(9)
        self.LE_monto_a.setFont(font)
        self.LE_monto_a.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}")
        self.LE_monto_a.setPlaceholderText("Monto adelantado")
        self.LE_monto_a.setObjectName("LE_monto_a")
        self.label_16 = QtWidgets.QLabel(self.GB_total_c)
        self.label_16.setGeometry(QtCore.QRect(190, 20, 31, 31))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("assets/icons/metodo-de-pago.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.GB_total_c)
        self.label_17.setGeometry(QtCore.QRect(10, 60, 31, 31))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("assets/icons/negocio.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.LE_subtotal = QtWidgets.QLineEdit(self.GB_total_c)
        self.LE_subtotal.setGeometry(QtCore.QRect(50, 20, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(9)
        self.LE_subtotal.setFont(font)
        self.LE_subtotal.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}")
        self.LE_subtotal.setPlaceholderText("Subtotal")
        self.LE_subtotal.setObjectName("LE_subtotal")
        self.LE_total = QtWidgets.QLineEdit(self.GB_total_c)
        self.LE_total.setGeometry(QtCore.QRect(230, 60, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(9)
        self.LE_total.setFont(font)
        self.LE_total.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}")
        self.LE_total.setPlaceholderText("Total")
        self.LE_total.setObjectName("LE_total")
        self.label_18 = QtWidgets.QLabel(self.GB_total_c)
        self.label_18.setGeometry(QtCore.QRect(190, 60, 31, 31))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("assets/icons/factura.png"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.label_20 = QtWidgets.QLabel(self.GB_total_c)
        self.label_20.setGeometry(QtCore.QRect(10, 20, 31, 31))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("assets/icons/dinero.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.GB_datos_e = QtWidgets.QGroupBox(self.frame)
        self.GB_datos_e.setGeometry(QtCore.QRect(30, 320, 281, 101))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        self.GB_datos_e.setFont(font)
        self.GB_datos_e.setStyleSheet("QGroupBox {\n"
"    border: 2px solid Black;\n"
"    border-radius: 5px;\n"
"}")
        self.GB_datos_e.setObjectName("GB_datos_e")
        self.label_7 = QtWidgets.QLabel(self.GB_datos_e)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.DT_fyh_salida_r = QtWidgets.QDateTimeEdit(self.GB_datos_e)
        self.DT_fyh_salida_r.setGeometry(QtCore.QRect(140, 20, 121, 31))
        self.DT_fyh_salida_r.setStyleSheet("QDateTimeEdit {\n"
"    color: #2C3E50;\n"
"    background-color: white;\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QDateTimeEdit:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}\n"
"\n"
"QCalendarWidget QWidget {\n"
"    alternate-background-color: #F8F9F9; \n"
"    background-color: white; \n"
"    color: black; \n"
"}")
        self.DT_fyh_salida_r.setReadOnly(True)
        self.DT_fyh_salida_r.setDate(QtCore.QDate(2026, 3, 27))
        self.DT_fyh_salida_r.setMinimumDate(QtCore.QDate(2010, 1, 1))
        self.DT_fyh_salida_r.setCalendarPopup(True)
        self.DT_fyh_salida_r.setTimeSpec(QtCore.Qt.LocalTime)
        self.DT_fyh_salida_r.setObjectName("DT_fyh_salida_r")
        self.label_10 = QtWidgets.QLabel(self.GB_datos_e)
        self.label_10.setGeometry(QtCore.QRect(40, 60, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.LE_dias_e = QtWidgets.QLineEdit(self.GB_datos_e)
        self.LE_dias_e.setGeometry(QtCore.QRect(140, 60, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(9)
        self.LE_dias_e.setFont(font)
        self.LE_dias_e.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}")
        self.LE_dias_e.setReadOnly(True)
        self.LE_dias_e.setPlaceholderText("Días")
        self.LE_dias_e.setObjectName("LE_dias_e")
        self.PB_checkout = QtWidgets.QPushButton(self.frame)
        self.PB_checkout.setGeometry(QtCore.QRect(40, 430, 111, 31))
        self.PB_checkout.setStyleSheet("QPushButton {\n"
"    background-color: #2C3E50;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #16A085;\n"
"}")
        self.PB_checkout.setObjectName("PB_checkout")
        self.PB_salir = QtWidgets.QPushButton(self.frame)
        self.PB_salir.setGeometry(QtCore.QRect(110, 470, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setBold(False)
        font.setWeight(50)
        self.PB_salir.setFont(font)
        self.PB_salir.setStyleSheet("color: #2C3E50;")
        self.PB_salir.setObjectName("PB_salir")
        self.PB_comprobante = QtWidgets.QPushButton(self.frame)
        self.PB_comprobante.setGeometry(QtCore.QRect(190, 430, 111, 31))
        self.PB_comprobante.setStyleSheet("QPushButton {\n"
"    background-color: #2C3E50;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #16A085;\n"
"}")
        self.PB_comprobante.setObjectName("PB_comprobante")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "CHECK-OUT"))
        self.GB_precioryc.setTitle(_translate("Dialog", "Precio de reserva y consumo"))
        item = self.TW_productos.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Producto"))
        item = self.TW_productos.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Cantidad"))
        item = self.TW_productos.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Subtotal"))
        self.PB_cargar_e.setText(_translate("Dialog", "CARGAR EXTRA"))
        self.GB_datos_cliente.setTitle(_translate("Dialog", "Datos del cliente:"))
        self.PB_buscar.setText(_translate("Dialog", "BUSCAR"))
        self.PB_cargar.setText(_translate("Dialog", "CARGAR"))
        self.GB_total_c.setTitle(_translate("Dialog", "Total y Comprobante"))
        self.GB_datos_e.setTitle(_translate("Dialog", "Datos de estadia"))
        self.label_7.setText(_translate("Dialog", "Fecha y hora de salida:"))
        self.DT_fyh_salida_r.setDisplayFormat(_translate("Dialog", "dd/MM/yy HH:mm"))
        self.label_10.setText(_translate("Dialog", "Dias de estancia:"))
        self.PB_checkout.setText(_translate("Dialog", "CHECK-OUT"))
        self.PB_salir.setText(_translate("Dialog", "SALIR"))
        self.PB_comprobante.setText(_translate("Dialog", "COMPROBANTE"))
