# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FrmCrear_reserva.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(951, 581)
        Dialog.setMinimumSize(QtCore.QSize(951, 581))
        Dialog.setMaximumSize(QtCore.QSize(951, 581))
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(100, 20, 761, 541))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("border-radius: 7px; background-color: #F4F6F6;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(410, 40, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 221, 61))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("assets/images/unnamed.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(40, 100, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(370, 100, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.PB_validar = QtWidgets.QPushButton(self.frame)
        self.PB_validar.setGeometry(QtCore.QRect(650, 100, 71, 31))
        self.PB_validar.setStyleSheet("QPushButton {\n"
"    background-color: #2C3E50;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #16A085;\n"
"}")
        self.PB_validar.setObjectName("PB_validar")
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(360, 210, 121, 1))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.GB_productos_a = QtWidgets.QGroupBox(self.frame)
        self.GB_productos_a.setGeometry(QtCore.QRect(340, 150, 391, 241))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        self.GB_productos_a.setFont(font)
        self.GB_productos_a.setStyleSheet("QGroupBox {\n"
"    border: 2px solid Black;\n"
"    border-radius: 5px;\n"
"}")
        self.GB_productos_a.setObjectName("GB_productos_a")
        self.CB_producto = QtWidgets.QComboBox(self.GB_productos_a)
        self.CB_producto.setGeometry(QtCore.QRect(50, 20, 131, 31))
        self.CB_producto.setStyleSheet("QComboBox {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}")
        self.CB_producto.setObjectName("CB_producto")
        self.label_11 = QtWidgets.QLabel(self.GB_productos_a)
        self.label_11.setGeometry(QtCore.QRect(10, 20, 31, 31))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("assets/icons/agregar-producto.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.SB_cantidad = QtWidgets.QSpinBox(self.GB_productos_a)
        self.SB_cantidad.setGeometry(QtCore.QRect(250, 20, 51, 31))
        self.SB_cantidad.setStyleSheet("QSpinBox {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QSpinBox:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}")
        self.SB_cantidad.setObjectName("SB_cantidad")
        self.label_12 = QtWidgets.QLabel(self.GB_productos_a)
        self.label_12.setGeometry(QtCore.QRect(210, 20, 31, 31))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("assets/icons/cantidad.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.TW_productos_c = QtWidgets.QTableWidget(self.GB_productos_a)
        self.TW_productos_c.setGeometry(QtCore.QRect(50, 70, 301, 131))
        self.TW_productos_c.setStyleSheet("QHeaderView::section {\n"
"    background-color: #2C3E50;\n"
"    color: white;\n"
"    padding: 5px;\n"
"    border: 1px solid #1A252F;\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QHeaderView::section:hover {\n"
"    background-color: #1ABC9C;\n"
"}")
        self.TW_productos_c.setRowCount(3)
        self.TW_productos_c.setObjectName("TW_productos_c")
        self.TW_productos_c.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.TW_productos_c.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TW_productos_c.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TW_productos_c.setHorizontalHeaderItem(2, item)
        self.TW_productos_c.verticalHeader().setVisible(False)
        self.label_13 = QtWidgets.QLabel(self.GB_productos_a)
        self.label_13.setGeometry(QtCore.QRect(30, 200, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.PB_cargar_2 = QtWidgets.QPushButton(self.GB_productos_a)
        self.PB_cargar_2.setGeometry(QtCore.QRect(310, 20, 71, 31))
        self.PB_cargar_2.setStyleSheet("QPushButton {\n"
"    background-color: #2C3E50;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #16A085;\n"
"}")
        self.PB_cargar_2.setObjectName("PB_cargar_2")
        self.LE_monto = QtWidgets.QLineEdit(self.GB_productos_a)
        self.LE_monto.setGeometry(QtCore.QRect(70, 200, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(9)
        self.LE_monto.setFont(font)
        self.LE_monto.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}")
        self.LE_monto.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.LE_monto.setReadOnly(True)
        self.LE_monto.setObjectName("LE_monto")
        self.DT_fyh_salida = QtWidgets.QDateTimeEdit(self.frame)
        self.DT_fyh_salida.setGeometry(QtCore.QRect(510, 100, 121, 31))
        self.DT_fyh_salida.setStyleSheet("QDateTimeEdit {\n"
"    color: #2C3E50;\n"
"    background-color: white;\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QDateTimeEdit:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}\n"
"\n"
"QCalendarWidget QWidget {\n"
"    alternate-background-color: #F8F9F9; \n"
"    background-color: white; \n"
"    color: black; \n"
"}")
        self.DT_fyh_salida.setDate(QtCore.QDate(2026, 3, 27))
        self.DT_fyh_salida.setMinimumDate(QtCore.QDate(2010, 1, 1))
        self.DT_fyh_salida.setCalendarPopup(True)
        self.DT_fyh_salida.setObjectName("DT_fyh_salida")
        self.DT_fyh_ingreso = QtWidgets.QDateTimeEdit(self.frame)
        self.DT_fyh_ingreso.setGeometry(QtCore.QRect(190, 100, 121, 31))
        self.DT_fyh_ingreso.setStyleSheet("QDateTimeEdit {\n"
"    color: #2C3E50;\n"
"    background-color: white;\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QDateTimeEdit:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}\n"
"\n"
"QCalendarWidget QWidget {\n"
"    alternate-background-color: #F8F9F9; \n"
"    background-color: white; \n"
"    color: black; \n"
"}")
        self.DT_fyh_ingreso.setDate(QtCore.QDate(2026, 3, 27))
        self.DT_fyh_ingreso.setMinimumDate(QtCore.QDate(2010, 1, 1))
        self.DT_fyh_ingreso.setCalendarPopup(True)
        self.DT_fyh_ingreso.setTimeSpec(QtCore.Qt.LocalTime)
        self.DT_fyh_ingreso.setObjectName("DT_fyh_ingreso")
        self.GB_datos_cliente = QtWidgets.QGroupBox(self.frame)
        self.GB_datos_cliente.setGeometry(QtCore.QRect(30, 150, 281, 241))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        self.GB_datos_cliente.setFont(font)
        self.GB_datos_cliente.setStyleSheet("QGroupBox {\n"
"    border: 2px solid Black;\n"
"    border-radius: 5px;\n"
"}")
        self.GB_datos_cliente.setObjectName("GB_datos_cliente")
        self.LE_numero_d = QtWidgets.QLineEdit(self.GB_datos_cliente)
        self.LE_numero_d.setGeometry(QtCore.QRect(50, 20, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(9)
        self.LE_numero_d.setFont(font)
        self.LE_numero_d.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}")
        self.LE_numero_d.setPlaceholderText("Ingrese documento")
        self.LE_numero_d.setObjectName("LE_numero_d")
        self.label_2 = QtWidgets.QLabel(self.GB_datos_cliente)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 31, 31))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("assets/icons/carnet-de-identidad.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.LE_nombres_apellidos = QtWidgets.QLineEdit(self.GB_datos_cliente)
        self.LE_nombres_apellidos.setGeometry(QtCore.QRect(50, 60, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(9)
        self.LE_nombres_apellidos.setFont(font)
        self.LE_nombres_apellidos.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}")
        self.LE_nombres_apellidos.setPlaceholderText("Nombres y apellidos")
        self.LE_nombres_apellidos.setObjectName("LE_nombres_apellidos")
        self.label_8 = QtWidgets.QLabel(self.GB_datos_cliente)
        self.label_8.setGeometry(QtCore.QRect(10, 60, 31, 31))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("assets/icons/usuario (1).png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.LE_contacto = QtWidgets.QLineEdit(self.GB_datos_cliente)
        self.LE_contacto.setGeometry(QtCore.QRect(50, 100, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(9)
        self.LE_contacto.setFont(font)
        self.LE_contacto.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}")
        self.LE_contacto.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.LE_contacto.setPlaceholderText("Contacto")
        self.LE_contacto.setObjectName("LE_contacto")
        self.label_9 = QtWidgets.QLabel(self.GB_datos_cliente)
        self.label_9.setGeometry(QtCore.QRect(10, 100, 31, 31))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("assets/icons/llamada-telefonica.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.GB_datos_cliente)
        self.label_10.setGeometry(QtCore.QRect(10, 140, 31, 31))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("assets/icons/correo-electronico.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.LE_correo = QtWidgets.QLineEdit(self.GB_datos_cliente)
        self.LE_correo.setGeometry(QtCore.QRect(50, 140, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(9)
        self.LE_correo.setFont(font)
        self.LE_correo.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}")
        self.LE_correo.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.LE_correo.setObjectName("LE_correo")
        self.PB_buscar = QtWidgets.QPushButton(self.GB_datos_cliente)
        self.PB_buscar.setGeometry(QtCore.QRect(190, 20, 71, 31))
        self.PB_buscar.setStyleSheet("QPushButton {\n"
"    background-color: #2C3E50;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #16A085;\n"
"}")
        self.PB_buscar.setObjectName("PB_buscar")
        self.PB_cargar = QtWidgets.QPushButton(self.GB_datos_cliente)
        self.PB_cargar.setGeometry(QtCore.QRect(50, 190, 171, 31))
        self.PB_cargar.setStyleSheet("QPushButton {\n"
"    background-color: #2C3E50;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #16A085;\n"
"}")
        self.PB_cargar.setObjectName("PB_cargar")
        self.GB_datos_r = QtWidgets.QGroupBox(self.frame)
        self.GB_datos_r.setGeometry(QtCore.QRect(30, 410, 701, 111))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        self.GB_datos_r.setFont(font)
        self.GB_datos_r.setStyleSheet("QGroupBox {\n"
"    border: 2px solid Black;\n"
"    border-radius: 5px;\n"
"}")
        self.GB_datos_r.setObjectName("GB_datos_r")
        self.LE_id_r = QtWidgets.QLineEdit(self.GB_datos_r)
        self.LE_id_r.setGeometry(QtCore.QRect(60, 20, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(9)
        self.LE_id_r.setFont(font)
        self.LE_id_r.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}")
        self.LE_id_r.setPlaceholderText("ID reserva")
        self.LE_id_r.setObjectName("LE_id_r")
        self.SB_numero_h = QtWidgets.QSpinBox(self.GB_datos_r)
        self.SB_numero_h.setGeometry(QtCore.QRect(320, 60, 51, 31))
        self.SB_numero_h.setStyleSheet("QSpinBox {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QSpinBox:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}")
        self.SB_numero_h.setObjectName("SB_numero_h")
        self.label_15 = QtWidgets.QLabel(self.GB_datos_r)
        self.label_15.setGeometry(QtCore.QRect(220, 60, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.CB_medio_p = QtWidgets.QComboBox(self.GB_datos_r)
        self.CB_medio_p.setGeometry(QtCore.QRect(420, 20, 131, 31))
        self.CB_medio_p.setStyleSheet("QComboBox {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}\n"
"")
        self.CB_medio_p.setObjectName("CB_medio_p")
        self.LE_monto_a = QtWidgets.QLineEdit(self.GB_datos_r)
        self.LE_monto_a.setGeometry(QtCore.QRect(420, 60, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(9)
        self.LE_monto_a.setFont(font)
        self.LE_monto_a.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}")
        self.LE_monto_a.setPlaceholderText("Monto adelantado")
        self.LE_monto_a.setObjectName("LE_monto_a")
        self.label_3 = QtWidgets.QLabel(self.GB_datos_r)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 31, 31))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("assets/icons/cita.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_16 = QtWidgets.QLabel(self.GB_datos_r)
        self.label_16.setGeometry(QtCore.QRect(380, 20, 31, 31))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("assets/icons/metodo-de-pago.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.GB_datos_r)
        self.label_17.setGeometry(QtCore.QRect(380, 60, 31, 31))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("assets/icons/negocio.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.PB_crear = QtWidgets.QPushButton(self.GB_datos_r)
        self.PB_crear.setGeometry(QtCore.QRect(570, 20, 111, 31))
        self.PB_crear.setStyleSheet("QPushButton {\n"
"    background-color: #2C3E50;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #16A085;\n"
"}")
        self.PB_crear.setObjectName("PB_crear")
        self.PB_salir = QtWidgets.QPushButton(self.GB_datos_r)
        self.PB_salir.setGeometry(QtCore.QRect(570, 60, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setBold(False)
        font.setWeight(50)
        self.PB_salir.setFont(font)
        self.PB_salir.setStyleSheet("color: #2C3E50;")
        self.PB_salir.setObjectName("PB_salir")
        self.CB_numero_h = QtWidgets.QComboBox(self.GB_datos_r)
        self.CB_numero_h.setGeometry(QtCore.QRect(60, 60, 131, 31))
        self.CB_numero_h.setStyleSheet("QComboBox {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}\n"
"")
        self.CB_numero_h.setObjectName("CB_numero_h")
        self.label_18 = QtWidgets.QLabel(self.GB_datos_r)
        self.label_18.setGeometry(QtCore.QRect(20, 60, 31, 31))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("assets/icons/cama (1).png"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.CB_tipo_h = QtWidgets.QComboBox(self.GB_datos_r)
        self.CB_tipo_h.setGeometry(QtCore.QRect(240, 20, 131, 31))
        self.CB_tipo_h.setStyleSheet("QComboBox {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}\n"
"")
        self.CB_tipo_h.setCurrentText("")
        self.CB_tipo_h.setObjectName("CB_tipo_h")
        self.label_19 = QtWidgets.QLabel(self.GB_datos_r)
        self.label_19.setGeometry(QtCore.QRect(200, 20, 31, 31))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("assets/icons/cama (1).png"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 951, 601))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("assets/images/imagen_login1.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label.raise_()
        self.frame.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "CREAR RESERVA"))
        self.label_6.setText(_translate("Dialog", "Fecha y hora de ingreso:"))
        self.label_7.setText(_translate("Dialog", "Fecha y hora de salida:"))
        self.PB_validar.setText(_translate("Dialog", "VALIDAR"))
        self.GB_productos_a.setTitle(_translate("Dialog", "Productos adicionales:"))
        item = self.TW_productos_c.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Producto"))
        item = self.TW_productos_c.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Cantidad"))
        item = self.TW_productos_c.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Subtotal"))
        self.label_13.setText(_translate("Dialog", "Total:"))
        self.PB_cargar_2.setText(_translate("Dialog", "CARGAR"))
        self.LE_monto.setPlaceholderText(_translate("Dialog", "Monto"))
        self.DT_fyh_salida.setDisplayFormat(_translate("Dialog", "dd/MM/yy HH:mm"))
        self.DT_fyh_ingreso.setDisplayFormat(_translate("Dialog", "dd/MM/yy HH:mm"))
        self.GB_datos_cliente.setTitle(_translate("Dialog", "Datos del cliente:"))
        self.LE_correo.setPlaceholderText(_translate("Dialog", "Correo"))
        self.PB_buscar.setText(_translate("Dialog", "BUSCAR"))
        self.PB_cargar.setText(_translate("Dialog", "CARGAR"))
        self.GB_datos_r.setTitle(_translate("Dialog", "Datos reserva:"))
        self.label_15.setText(_translate("Dialog", "N\" de huespedes"))
        self.PB_crear.setText(_translate("Dialog", "CREAR"))
        self.PB_salir.setText(_translate("Dialog", "SALIR"))
