# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FrmCheckin.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(770, 470)
        Dialog.setMinimumSize(QtCore.QSize(770, 470))
        Dialog.setMaximumSize(QtCore.QSize(770, 470))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 771, 471))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("assets/images/imagen_login1.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(130, 10, 511, 451))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("border-radius: 7px; background-color: #F4F6F6;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(280, 40, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 171, 61))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("assets/images/unnamed.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.LE_numero_d = QtWidgets.QLineEdit(self.frame)
        self.LE_numero_d.setGeometry(QtCore.QRect(170, 90, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(9)
        self.LE_numero_d.setFont(font)
        self.LE_numero_d.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}")
        self.LE_numero_d.setPlaceholderText("Ingrese documento")
        self.LE_numero_d.setObjectName("LE_numero_d")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(130, 90, 31, 31))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("assets/icons/carnet-de-identidad.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.PB_buscar = QtWidgets.QPushButton(self.frame)
        self.PB_buscar.setGeometry(QtCore.QRect(310, 90, 91, 31))
        self.PB_buscar.setStyleSheet("QPushButton {\n"
"    background-color: #2C3E50;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #16A085;\n"
"}")
        self.PB_buscar.setObjectName("PB_buscar")
        self.GB_datos_r = QtWidgets.QGroupBox(self.frame)
        self.GB_datos_r.setGeometry(QtCore.QRect(30, 140, 461, 301))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        self.GB_datos_r.setFont(font)
        self.GB_datos_r.setStyleSheet("QGroupBox {\n"
"    border: 2px solid Black;\n"
"    border-radius: 5px;\n"
"}")
        self.GB_datos_r.setObjectName("GB_datos_r")
        self.LE_id_r = QtWidgets.QLineEdit(self.GB_datos_r)
        self.LE_id_r.setGeometry(QtCore.QRect(60, 20, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(9)
        self.LE_id_r.setFont(font)
        self.LE_id_r.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}")
        self.LE_id_r.setReadOnly(True)
        self.LE_id_r.setPlaceholderText("ID reserva")
        self.LE_id_r.setObjectName("LE_id_r")
        self.SB_numero_h = QtWidgets.QSpinBox(self.GB_datos_r)
        self.SB_numero_h.setGeometry(QtCore.QRect(140, 140, 51, 31))
        self.SB_numero_h.setStyleSheet("QSpinBox {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QSpinBox:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}")
        self.SB_numero_h.setReadOnly(True)
        self.SB_numero_h.setObjectName("SB_numero_h")
        self.label_15 = QtWidgets.QLabel(self.GB_datos_r)
        self.label_15.setGeometry(QtCore.QRect(30, 140, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.CB_medio_p = QtWidgets.QComboBox(self.GB_datos_r)
        self.CB_medio_p.setGeometry(QtCore.QRect(300, 20, 131, 31))
        self.CB_medio_p.setStyleSheet("QComboBox {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}\n"
"")
        self.CB_medio_p.setObjectName("CB_medio_p")
        self.LE_monto_a = QtWidgets.QLineEdit(self.GB_datos_r)
        self.LE_monto_a.setGeometry(QtCore.QRect(60, 180, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(9)
        self.LE_monto_a.setFont(font)
        self.LE_monto_a.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}")
        self.LE_monto_a.setReadOnly(True)
        self.LE_monto_a.setPlaceholderText("Monto adelantado")
        self.LE_monto_a.setObjectName("LE_monto_a")
        self.label_11 = QtWidgets.QLabel(self.GB_datos_r)
        self.label_11.setGeometry(QtCore.QRect(20, 20, 31, 31))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("assets/icons/cita.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_16 = QtWidgets.QLabel(self.GB_datos_r)
        self.label_16.setGeometry(QtCore.QRect(260, 20, 31, 31))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("assets/icons/metodo-de-pago.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.GB_datos_r)
        self.label_17.setGeometry(QtCore.QRect(20, 180, 31, 31))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("assets/icons/negocio.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.CB_numero_h = QtWidgets.QComboBox(self.GB_datos_r)
        self.CB_numero_h.setEnabled(False)
        self.CB_numero_h.setGeometry(QtCore.QRect(60, 60, 131, 31))
        self.CB_numero_h.setStyleSheet("QComboBox {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}\n"
"")
        self.CB_numero_h.setEditable(False)
        self.CB_numero_h.setObjectName("CB_numero_h")
        self.label_18 = QtWidgets.QLabel(self.GB_datos_r)
        self.label_18.setGeometry(QtCore.QRect(20, 60, 31, 31))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("assets/icons/cama (1).png"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.LE_contacto = QtWidgets.QLineEdit(self.GB_datos_r)
        self.LE_contacto.setGeometry(QtCore.QRect(300, 100, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(9)
        self.LE_contacto.setFont(font)
        self.LE_contacto.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}")
        self.LE_contacto.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.LE_contacto.setReadOnly(True)
        self.LE_contacto.setPlaceholderText("Contacto")
        self.LE_contacto.setObjectName("LE_contacto")
        self.LE_nombres_apellidos = QtWidgets.QLineEdit(self.GB_datos_r)
        self.LE_nombres_apellidos.setGeometry(QtCore.QRect(300, 60, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(9)
        self.LE_nombres_apellidos.setFont(font)
        self.LE_nombres_apellidos.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}")
        self.LE_nombres_apellidos.setReadOnly(True)
        self.LE_nombres_apellidos.setPlaceholderText("Nombres y apellidos")
        self.LE_nombres_apellidos.setObjectName("LE_nombres_apellidos")
        self.label_6 = QtWidgets.QLabel(self.GB_datos_r)
        self.label_6.setGeometry(QtCore.QRect(260, 60, 31, 31))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("assets/icons/usuario (1).png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.GB_datos_r)
        self.label_7.setGeometry(QtCore.QRect(260, 100, 31, 31))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("assets/icons/llamada-telefonica.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.PB_salir = QtWidgets.QPushButton(self.GB_datos_r)
        self.PB_salir.setGeometry(QtCore.QRect(210, 260, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setBold(False)
        font.setWeight(50)
        self.PB_salir.setFont(font)
        self.PB_salir.setStyleSheet("color: #2C3E50;")
        self.PB_salir.setObjectName("PB_salir")
        self.PB_marcar_checkin = QtWidgets.QPushButton(self.GB_datos_r)
        self.PB_marcar_checkin.setGeometry(QtCore.QRect(150, 230, 171, 31))
        self.PB_marcar_checkin.setStyleSheet("QPushButton {\n"
"    background-color: #2C3E50;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #16A085;\n"
"}")
        self.PB_marcar_checkin.setObjectName("PB_marcar_checkin")
        self.DT_fyh_salida = QtWidgets.QDateTimeEdit(self.GB_datos_r)
        self.DT_fyh_salida.setGeometry(QtCore.QRect(300, 180, 131, 31))
        self.DT_fyh_salida.setStyleSheet("QDateTimeEdit {\n"
"    color: #2C3E50;\n"
"    background-color: white;\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QDateTimeEdit:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}\n"
"\n"
"QCalendarWidget QWidget {\n"
"    alternate-background-color: #F8F9F9; \n"
"    background-color: white; \n"
"    color: black; \n"
"}")
        self.DT_fyh_salida.setReadOnly(True)
        self.DT_fyh_salida.setDate(QtCore.QDate(2026, 3, 27))
        self.DT_fyh_salida.setMinimumDate(QtCore.QDate(2010, 1, 1))
        self.DT_fyh_salida.setCalendarPopup(True)
        self.DT_fyh_salida.setTimeSpec(QtCore.Qt.LocalTime)
        self.DT_fyh_salida.setObjectName("DT_fyh_salida")
        self.DT_fyh_ingreso = QtWidgets.QDateTimeEdit(self.GB_datos_r)
        self.DT_fyh_ingreso.setGeometry(QtCore.QRect(300, 140, 131, 31))
        self.DT_fyh_ingreso.setStyleSheet("QDateTimeEdit {\n"
"    color: #2C3E50;\n"
"    background-color: white;\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QDateTimeEdit:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}\n"
"\n"
"QCalendarWidget QWidget {\n"
"    alternate-background-color: #F8F9F9; \n"
"    background-color: white; \n"
"    color: black; \n"
"}")
        self.DT_fyh_ingreso.setReadOnly(True)
        self.DT_fyh_ingreso.setDate(QtCore.QDate(2026, 3, 27))
        self.DT_fyh_ingreso.setMinimumDate(QtCore.QDate(2010, 1, 1))
        self.DT_fyh_ingreso.setCalendarPopup(True)
        self.DT_fyh_ingreso.setObjectName("DT_fyh_ingreso")
        self.label_8 = QtWidgets.QLabel(self.GB_datos_r)
        self.label_8.setGeometry(QtCore.QRect(260, 140, 31, 31))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("assets/icons/lista-de-verificacion (1).png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.GB_datos_r)
        self.label_9.setGeometry(QtCore.QRect(260, 180, 31, 31))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("../ICONOS/reloj-de-salida.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.CB_tipo_h = QtWidgets.QComboBox(self.GB_datos_r)
        self.CB_tipo_h.setEnabled(False)
        self.CB_tipo_h.setGeometry(QtCore.QRect(60, 100, 131, 31))
        self.CB_tipo_h.setStyleSheet("QComboBox {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}\n"
"")
        self.CB_tipo_h.setEditable(False)
        self.CB_tipo_h.setObjectName("CB_tipo_h")
        self.label_19 = QtWidgets.QLabel(self.GB_datos_r)
        self.label_19.setGeometry(QtCore.QRect(20, 100, 31, 31))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("assets/icons/cama (1).png"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "CHECK-IN"))
        self.PB_buscar.setText(_translate("Dialog", "BUSCAR"))
        self.GB_datos_r.setTitle(_translate("Dialog", "Datos reserva:"))
        self.label_15.setText(_translate("Dialog", "N\" de huespedes"))
        self.PB_salir.setText(_translate("Dialog", "SALIR"))
        self.PB_marcar_checkin.setText(_translate("Dialog", "MARCAR CHECK-IN"))
        self.DT_fyh_salida.setDisplayFormat(_translate("Dialog", "dd/MM/yy HH:mm"))
        self.DT_fyh_ingreso.setDisplayFormat(_translate("Dialog", "dd/MM/yy HH:mm"))
