# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FrmRegistro.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(659, 379)
        Dialog.setMinimumSize(QtCore.QSize(659, 379))
        Dialog.setMaximumSize(QtCore.QSize(659, 379))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 661, 381))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("assets/images/imagen_login1.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(100, 10, 441, 361))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("border-radius: 7px; background-color: #F4F6F6;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.LE_correo = QtWidgets.QLineEdit(self.frame)
        self.LE_correo.setGeometry(QtCore.QRect(70, 160, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(9)
        self.LE_correo.setFont(font)
        self.LE_correo.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}")
        self.LE_correo.setPlaceholderText("Correo")
        self.LE_correo.setObjectName("LE_correo")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(30, 160, 31, 31))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("assets/icons/usuario.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(230, 220, 31, 31))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("assets/icons/cerrar-con-llave.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.PB_registrar = QtWidgets.QPushButton(self.frame)
        self.PB_registrar.setGeometry(QtCore.QRect(130, 290, 161, 31))
        self.PB_registrar.setStyleSheet("QPushButton {\n"
"    background-color: #2C3E50;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #16A085;\n"
"}")
        self.PB_registrar.setObjectName("PB_registrar")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(130, 90, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(140, 20, 171, 61))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("assets/images/unnamed.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.PB_iniciar_s = QtWidgets.QPushButton(self.frame)
        self.PB_iniciar_s.setGeometry(QtCore.QRect(170, 320, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setBold(False)
        font.setWeight(50)
        self.PB_iniciar_s.setFont(font)
        self.PB_iniciar_s.setStyleSheet("color: #2C3E50;")
        self.PB_iniciar_s.setObjectName("PB_iniciar_s")
        self.LE_nombres = QtWidgets.QLineEdit(self.frame)
        self.LE_nombres.setGeometry(QtCore.QRect(70, 120, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(9)
        self.LE_nombres.setFont(font)
        self.LE_nombres.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}")
        self.LE_nombres.setPlaceholderText("Nombres")
        self.LE_nombres.setObjectName("LE_nombres")
        self.CB_roles = QtWidgets.QComboBox(self.frame)
        self.CB_roles.setGeometry(QtCore.QRect(70, 200, 131, 31))
        self.CB_roles.setStyleSheet("QComboBox {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}")
        self.CB_roles.setObjectName("CB_roles")
        self.LE_contrasena = QtWidgets.QLineEdit(self.frame)
        self.LE_contrasena.setGeometry(QtCore.QRect(270, 180, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(9)
        self.LE_contrasena.setFont(font)
        self.LE_contrasena.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}")
        self.LE_contrasena.setEchoMode(QtWidgets.QLineEdit.Password)
        self.LE_contrasena.setObjectName("LE_contrasena")
        self.LE_cocontrasena = QtWidgets.QLineEdit(self.frame)
        self.LE_cocontrasena.setGeometry(QtCore.QRect(270, 220, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(9)
        self.LE_cocontrasena.setFont(font)
        self.LE_cocontrasena.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}")
        self.LE_cocontrasena.setEchoMode(QtWidgets.QLineEdit.Password)
        self.LE_cocontrasena.setObjectName("LE_cocontrasena")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(230, 180, 31, 31))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("assets/icons/cerrar-con-llave.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(30, 120, 31, 31))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("assets/icons/usuario (1).png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(30, 200, 31, 31))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("assets/icons/grupos.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.LE_respuesta = QtWidgets.QLineEdit(self.frame)
        self.LE_respuesta.setGeometry(QtCore.QRect(270, 140, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(9)
        self.LE_respuesta.setFont(font)
        self.LE_respuesta.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}")
        self.LE_respuesta.setEchoMode(QtWidgets.QLineEdit.Password)
        self.LE_respuesta.setObjectName("LE_respuesta")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(230, 140, 31, 31))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("assets/icons/marca-de-verificacion.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.CB_pregunta_s = QtWidgets.QComboBox(self.frame)
        self.CB_pregunta_s.setGeometry(QtCore.QRect(70, 240, 131, 31))
        self.CB_pregunta_s.setStyleSheet("QComboBox {\n"
"    border: 2px solid #D5DBDB;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 2px solid #2C3E50;\n"
"}")
        self.CB_pregunta_s.setObjectName("CB_pregunta_s")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(30, 240, 31, 31))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("assets/icons/seguridad.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.PB_registrar.setText(_translate("Dialog", "REGISTRAR"))
        self.label_4.setText(_translate("Dialog", "REGISTRAR NUEVO USUARIO"))
        self.PB_iniciar_s.setText(_translate("Dialog", "INICIAR SESION"))
        self.LE_contrasena.setPlaceholderText(_translate("Dialog", "Contraseña"))
        self.LE_cocontrasena.setPlaceholderText(_translate("Dialog", "Confirmar contraseña"))
        self.LE_respuesta.setPlaceholderText(_translate("Dialog", "Respuesta"))
